export const keywords = [
  "react",
  "hooks",
  "typescript",
  "library",
  "rehooks",
  "next",
  "javascript",
  "mdx",
  "docs",
  "tailwindcss",
  "mehdi",
  "pyr33x",
  "mehdi parandak",
  "mahdi",
  "mahdi parandak",
  "turbo",
  "monorepo",
  "turborepo",
  "turbopack",
  "vercel",
  "upstash",
  "redis",
  "api",
  "ratelimit",
  "cli",
  "npx",
  "npm",
  "react ecosystem",
  "react hooks",
  "reusable hooks",
  "react reusable hooks",
  "react hooks best practice",
  "hooks cli",
  "react hooks cli",
  "react typescript hooks",
  "usehooks",
  "rehooks-ts",
  "pyr33x",
  "pyrex",
];
